### 0.데이터 다운로드


In [ ]:
!git clone https://github.com/Soyoung-Yoon/data_02

Cloning into 'data_02'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 50 (delta 0), reused 0 (delta 0), pack-reused 47
Unpacking objects: 100% (50/50), 442.37 KiB | 1022.00 KiB/s, done.


In [ ]:
import scipy
scipy.__version__

In [ ]:
!pip install scipy==1.6.0

### 1.카이제곱 적합도 검정

####1-1.특정비율
A학급 40명의 혈액형 비율을 A, B, O, AB 각각 20%, 20%, 30%, 30%로 예상하였다. 실제 측정 결과 16, 16, 4, 4 명인 경우의 적합도 검정을 수행하여 보자


- 𝑯_𝟎 : 변수의 분포가 기대 분포와 같다
- 𝑯_𝟏 : 변수의 분포가 기대 분포와 같지 않다


In [ ]:
# [파일로 주어진 경우 직접 개수 계산]
import pandas as pd
data = {'blood_type': ['A']*16 + ['B']*16 + ['C']*4 + ['D']*4}
data = pd.DataFrame(data)
observed = None
print(observed)

In [ ]:
from scipy.stats import chisquare
import numpy as np


#### 1-2.동일비율
4개의 범주에 대해 동일한 비율이라고 가정하고, 실제측정 한 표본 분포가 다음과 같을 때, 카이제곱 적합도 검정을 수행하여 보자

        observed = [54, 46, 60, 40]


- 𝑯_𝟎 : 변수의 분포에 비율 차이가 없다.
- 𝑯_𝟏 : 변수의 분포에 비율 차이가 있다.

In [ ]:
from scipy.stats import chisquare
import numpy as np


### 2.카이제곱 동질성/독립성 검정
- 두 범주형 자료 간의 차이를 분석하는 검증 방법
- 관찰빈도(실제값)가 기대빈도(기댓값)와 유의한 차이가 있는지 검증
- 관찰빈도는 절대적 수치로만 관찰되어야 함, 기대빈도의 합과 관찰빈도의 합은 같음
- 분할표의 칸 수 및 각 칸의 기대빈도는 5이상 이어야 함
- 귀무가설이 기각되면 범주별 기대빈도와 관측빈도의 차이가 충분히 크다고 말할 수 있음
- 기대빈도와 관찰빈도의 차이가 커지면 카이제곱 통계량도 커짐


#### 2-1.카이제곱 동질성 검정
- H0 : 성별별 핸드폰 모델 선호도 분포는 같다
- H1 : 성별별 핸드폰 모델 선호도 분포가 같지 않다

In [ ]:
import pandas as pd
from scipy.stats import chi2_contingency

crs_table = pd.DataFrame([[10, 40, 50], [30, 60, 10]], 
                         index=['M', 'F'], 
                columns=['model_A', 'model_B', 'model_C'])
print(crs_table)

####2-2.카이제곱 독립성 검정
- 귀무가설 : 당뇨와 비만 사이에 관계는 독립이다.
-대립가설 : 당뇨와 비만 사이에 관계는 독립이 아니다.

In [ ]:
# [1] 데이터 가져오기
import pandas as pd
from scipy.stats import chi2_contingency
data = pd.read_csv("data_02/data_chi.csv")
print(data)

In [ ]:
# [2] 카이제곱 분석을 위한 분할표 만들기


In [ ]:
# [3] 카이스퀘어 분석


In [ ]:
# [4] 결론


#### 2-3.피셔의 정확검정
- 만약 사건 발생 수, 빈도 수가 극히 적거나(특히 5개 이하의 빈도가 전체 셀 중 20%이상 존재하는 경우) 서로의 빈도 수의 차이가 많이나는 경우에는 카이제곱 검정의 정확도는 낮아집니다. 
- 이때 필요한 검정이 바로 '피셔의 정확검정'입니다.

가설설정
- 귀무가설 : 약과 효과의 관계는 독립이다. 
- 대립가설 : 약과 효과의 관계가 독립이 아니다.

In [ ]:
import pandas as pd
from scipy.stats import fisher_exact

# [1] 분할표 생성
data = pd.DataFrame([[1, 6], [5, 2]])
data.columns = ['가짜 약','진짜 약']
data.index = ['효과있음', '효과없음']
print(data)

In [ ]:
# [2] 피셔 검정


In [ ]:
help(fisher_exact)

In [ ]:
# [3] 결과


####2-4.아내와 남편의 집안일
- 귀무가설 : 집안일의 종류와 수행하는 사람의 관계는 독립이다.
- 대립가설 : 집안일의 종류와 수행하는 사람의 관계가 독립이 아니다.

In [ ]:
# [1] crosstable 형태의 데이터 읽기
import pandas as pd

data = pd.read_csv('housetasks.csv', index_col=0)
print(data.shape)
print(data.info())

(13, 4)
<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, Laundry to Holidays
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Wife         13 non-null     int64
 1   Alternating  13 non-null     int64
 2   Husband      13 non-null     int64
 3   Jointly      13 non-null     int64
dtypes: int64(4)
memory usage: 520.0+ bytes
None


In [ ]:
# [2] 카이제곱 독립성 검정
from scipy.stats import chi2_contingency



In [ ]:
# [3] 결과


####2-5.분류 모델에서 활용
- 2개 범주형 변수의 관계에 대해 검정한다

In [ ]:
# [1] 파일 불러오기
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/Soyoung-Yoon/bigdata/main/1st_Train.csv')
X = data.drop(columns=['Reached.on.Time_Y.N'])
Y = data[['ID', 'Reached.on.Time_Y.N']]

In [ ]:
#[2] X,Y가 분리되어 있는 경우 병합하기


#[3] 컬럼별 값의 가짓수 확인하기


In [ ]:
#[4] 범주형 변수 확인하기 
# (설명을 보고 확인하는 것이 정확함)


- (독립)범주형 변수 : 'Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender', 'Customer_rating', 'Customer_care_calls', 'Prior_purchases'
- (종속)범주형 변수 : 'Reached.on.Time_Y.N'
- 귀무가설 : 'Reached.on.Time_Y.N'과 feature는 독립이다. (연관성이 없다.)
- 대립가설 : 'Reached.on.Time_Y.N'과 feature는 독립이 아니다. (연관성이 있다.)


In [ ]:
# [5] 카이제곱 독립성 검정
from scipy.stats import chi2_contingency



In [ ]:
# [6] 결론


In [ ]:
def my_chi2(data, feature, target):
    pass


### 3.Wilcoxon Signed Rank Test
- 일표본/대응표본 T검정에서 정규성 가정이 만족되지 않을 때 사용하는 비모수 검정법
- 일표본/대응표본 T검정과는 달리 **중앙값에 관한 결과를 얻을 수 있음**.
- 가정
  1. 표본은 동일한 모집단에서 추출되어야 한다.
  2. 표본은 임의, 독립적으로 추출되어야 한다.

#### 3-1.일표본(One Sample)
- alternative='two-sided'
   - H0: 모집단의 중앙값은 A 이다.
   - H1: 모집단의 중앙값은 A가 아니다.
- alternative='less'
   - H0: 모집단의 중앙값은 A보다 크거나 같다.
   - H1: 모집단의 중앙값은 A보다 작다.
- alternative='greater'
   - H0: 모집단의 중앙값은 A보다 작거나 같다.
   - H1: 모집단의 중앙값은 A보다 크다.    

중량이 100g 으로 표기된 닭가슴살 제품이 100g이라고 할 수 있는가?
- 동일한 회사 제품을 임의로 9개 표본 추출하였음
- 통계적 유의수준은 0.05로 사용함
- H0: 닭 가슴살 중량의 중앙값은 100g이다
- H1: 닭 가슴살 중량의 중앙값은 100g이 아니다

In [ ]:
# [1] 데이터 가져오기
import pandas as pd
df = pd.read_csv('data_02/chicken_breast.csv')
print(df)

       weight
0  107.704526
1   96.505220
2  109.417631
3  109.696405
4   90.783694
5  107.871426
6  106.447983
7  104.484894
8   95.778403


In [ ]:
# [2] 중앙값 구하기


In [ ]:
# [3] 윌콕슨 검정 실행
from scipy.stats import wilcoxon


In [ ]:
# [4] 결과


alternative='less'
- H0: 닭가슴살 중량의 중앙값은 100 보다 크거나 같다.
- H1: 닭가슴살 중량의 중앙값은 100 보다 작다.

In [ ]:
from scipy.stats import wilcoxon


alternative='greater'
- H0: 닭가슴살 중량의 중앙값은 100 보다 작거나 같다.
- H1: 닭가슴살 중량의 중앙값은 100 보다 크다.

In [ ]:
from scipy.stats import wilcoxon


#### 3-2.대응표본(Paired)
- alternative='two-sided'
    - H0: 값 차이(처리후 - 처리전)의 중앙값이 0이다(=값의 차이가 없다)
    - H1: 값 차이(처리후 - 처리전)의 중앙값이 0이 아니다(=값의 차이가 있다)
- alternative='less'
    - H0: 값 차이(처리후 - 처리전)의 중앙값이 0보다 크거나 같다
    - H1: 값 차이(처리후 - 처리전)의 중앙값이 0보다 작다
- alternative='greater'
    - H0: 값 차이(처리후 - 처리전)의 중앙값이 0보다 작거나 같다
    - H1: 값 차이(처리후 - 처리전)의 중앙값이 0보다 크다 

다이어트 후, 체중이 줄었다고 할 수 있는가? 몸무게 : 비율척도
- 동일한 회사 제품을 임의로 8개 표본 추출하였음
- 통계적 유의수준은 0.05로 사용함


alternative='less'
- H0: 다이어트 후 - 다이어트 전 몸무게 중앙값은 0보다 크거나 같다 
- H1: 다이어트 후 - 다이어트 전 몸무게 중앙값은 0보다 작다.

In [ ]:
# [1] 파일 불러오기
import pandas as pd
df = pd.read_csv('data_02/diet_result.csv')
print(df)

      before      after
0  60.038972  56.153355
1  58.566940  55.678046
2  62.200320  63.010597
3  68.522263  64.413353
4  54.802465  52.110032
5  55.437637  51.330742
6  64.700073  62.047727
7  65.030917  61.157653


In [ ]:
# scipy.stats.wilcoxon(x, y=None, zero_method='wilcox', correction=False, alternative='two-sided', mode='auto')
# The Wilcoxon signed-rank test tests the null hypothesis that two related paired samples come from the same distribution. 
# In particular, it tests whether the distribution of the differences x - y is symmetric about zero.
# It is a non-parametric version of the paired T-test.

In [ ]:
# [2] wilcoxon sign rank sum - (paired t-test의 비모수)
from scipy.stats import wilcoxon


In [ ]:
# [3] 결과


alternative='two-sided'
- H0: 다이어트 후 - 다이어트 전 몸무게 중앙값은 0과 같다 
- H1: 다이어트 후 - 다이어트 전 몸무게 중앙값은 0과 다르다

In [ ]:
from scipy.stats import wilcoxon


alternative='greater'
- H0: 다이어트 후 - 다이어트 전 몸무게 중앙값은 0보다 작거나 같다 
- H1: 다이어트 후 - 다이어트 전 몸무게 중앙값은 0보다 크다

In [ ]:
from scipy.stats import wilcoxon


###4.독립 2표본(Two Sample)
- 독립 2표본 T검정에서 정규성 가정이 만족되지 않을 때 사용하는 비모수 검정법
- **두 표본의 중위수를 비교**하는데 쓰임
- 가정
   1. 두 그룹은 독립적이다
   2. 측정값은 최소 순서형 변수이다(대소 비교가 가능해야 함)

   

- alternative='two-sided'
    - H0: gA의 중앙값과 gB의 중앙값이 같다(차이가 없다)
    - H1: gA의 중앙값과 gB의 중앙값이 다르다(차이가 있다)
- alternative='less'
    - H0: gA의 중앙값이 gB의 중앙값보다 크거나 같다
    - H1: gA의 중앙값이 gB의 중앙값보다 작다
- alternative='greater'
    - H0: gA의 중앙값이 gB의 중앙값보다 작거나 같다
    - H1: gA의 중앙값이 gB의 중앙값보다 크다

#### 4-1.Wilcoxon Rank Sum Test

A사 닭가슴살 제품의 중량과 B사 닭가슴살 제품의 중량이 차이가 있는지 확인
- A사 닭가슴살은 40개의 표본, B사 닭가슴살은 20개의 표본이 있으며
- 각각 독립적이고 임의로 추출했다
- 통계적 유의수준은 0.05 사용


alternative='two-sided'
- H0: A사 닭가슴살 중량과 B사 닭가슴살 중량의 차이가 없다
- H1: A사 닭가슴살 중량과 B사 닭가슴살 중량의 차이가 있다

In [ ]:
# [1] 파일 불러오기
import pandas as pd
df = pd.read_csv('data_02/chicken_weight_AB.csv')
df

In [ ]:
# [2] 그룹 나누기


scipy.stats.ranksums(x, y, alternative='two-sided')
- Compute the Wilcoxon rank-sum statistic for two samples.
- The Wilcoxon rank-sum test tests the null hypothesis that two sets of measurements are drawn from the same distribution. 
- The alternative hypothesis is that values in one sample are more likely to be larger than the values in the other sample.

- This test should be used to compare two samples from continuous distributions. 
- It does not handle ties between measurements in x and y. For tie-handling and an optional continuity correction see scipy.stats.mannwhitneyu.

In [ ]:
# [3] wilcoxon rank sum test (two sample)
from scipy.stats import ranksums


In [ ]:
# [4] 결과


alternative='less'
- H0: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 크거나 같다
- H1: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 작다

In [ ]:
# wilcoxon rank sum test (two sample)


alternative='greater'
- H0: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 작거나 같다
- H1: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 크다

In [ ]:
# wilcoxon rank sum test (two sample)
from scipy.stats import ranksums


#### 4-2.Mann-Whitney U test

scipy.stats.mannwhitneyu(x, y, use_continuity=True, alternative='two-sided', axis=0, method='auto')
- Perform the Mann-Whitney U rank test on two independent samples.
- The Mann-Whitney U test is a nonparametric test of the null hypothesis that the distribution underlying sample x is the same as the distribution underlying sample y. 


alternative='two-sided'
- H0: A사 닭가슴살 중량과 B사 닭가슴살 중량의 차이가 없다
- H1: A사 닭가슴살 중량과 B사 닭가슴살 중량의 차이가 있다

In [ ]:
# [1] Mann-Whitney U test (two sample)
from scipy.stats import mannwhitneyu


In [ ]:
# [2] 결과


alternative='less'
- H0: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 크거나 같다
- H1: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 작다

alternative='greater'
- H0: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 작거나 같다
- H1: A사 닭가슴살 중량이 B사 닭가슴살 중량보다 크다

### 5.Kruskal-Wallis H-test
- 분산 분석(ANOVA)에서 정규성 가정이 만족되지 않을 때 사용하는 비모수 검정법
- ANOVA와는 달리 중앙값에 관한 결과를 얻을 수 있음
- 가정
  1. 표본은 독립적이다.
  2. 측정값은 최소 순서형 변수이다. (대소 비교가 가능해야 합니다.)
- 가설
  - H0: 모든 그룹의 중앙값은 서로 같다
  - H1: 모든 그룹의 중앙값이 전부 같은 것은 아니다

scipy.stats.kruskal(*args, nan_policy='propagate')[source]
- The Kruskal-Wallis H-test tests the null hypothesis that the population median of all of the groups are equal. 
- It is a non-parametric version of ANOVA. The test works on 2 or more independent samples, which may have different sizes. 
- Note that rejecting the null hypothesis does not indicate which of the groups differs. 
- Post hoc comparisons between groups are required to determine which groups are different.

####5-1.K개 Sample
- A, B, C 고등학교 학생들의 하루 공부 시간을 조사했을 때,고등학교 간에 공부 시간이 차이가 있는지 확인
- 통계적 유의수준은 0.05


- H0: A,B,C 고등학교 학생들의 하루 공부시간에 차이가 없다
- H1: A,B,C 고등학교 학생들의 하루 공부시간에 차이가 있다

In [ ]:
# [1] 파일 불러오기
import pandas as pd
df = pd.read_csv('data_02/high_school.csv')
df.head(2)

group       time
0     A  12.525909
1     A   9.347533

In [ ]:
# [2] 그룹 나누기


In [ ]:
# [3] Kruskal-Wallis Test
from scipy.stats import kruskal


In [ ]:
# [4] 결과


In [ ]:
# [5] ANOVA Test


In [ ]:
# 등분산성 검정은??  (강의 내용에 없지만 확인!)
from scipy.stats import bartlett
bartlett(gA, gB, gC)

#### 5-2.분류 모델에서 활용
- 1개 연속형 변수, 1개 범주형 변수 (4개 범주)
- 범주별로 연속형 변수의 평균 차이가 있는지 검정한다

In [ ]:
# [1] 데이터 읽어오기 (4회기출)
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/Soyoung-Yoon/bigdata/main/train_04.csv')
data.head(2)

ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0  462809    Male           No   22        No  Healthcare              1.0   
1  466315  Female          Yes   67       Yes    Engineer              1.0   

  Spending_Score  Family_Size  Var_1  Segmentation  
0            Low          4.0  Cat_4             4  
1            Low          1.0  Cat_6             2

In [ ]:
# [2] 그룹 나누기 - 종속변수 Age, 독립변수 Segmentation
groups = [x.values for _, x in data.groupby('Segmentation')['Age']]
groups

[array([26, 49, 33, ..., 39, 31, 48]),
 array([67, 67, 58, ..., 41, 27, 37]),
 array([56, 32, 55, ..., 52, 37, 65]),
 array([22, 33, 61, ..., 39, 35, 33])]

In [ ]:
# [3] 정규성 검정
from scipy.stats import shapiro


In [ ]:
# [4] 'Segmentation' 그룹별 'Age'의 중앙값 구하기


In [ ]:
# [5] 크루스칼-왈리스 검정 수행
# 귀무가설 : Segmentation별 Age의 차이가 없다
# 대립가설 : Segmentation별 Age의 차이가 있다
from scipy.stats import kruskal
